openapi: 3.0.0
info:
  title: openapi.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Model_v1:
      title: Model_v1
      type: object
      properties:
        id:
          type: string
